#!/bin/bash

# Setup script to link dotfiles to the home directory
sync_file() {
    local src="$HOME/.files/$1"
    local dest="$HOME/.$1"

    if [ -e "$dest" ]; then
        echo "Found .$1 in home directory."
        if [ ! -L "$dest" ]; then
            echo "Moving .$1 to .$1.old"
            mv -iv "$dest" "$dest.old"
        fi
    fi
    echo "Linking $1..."
    ln -sfv "$src" "$dest"
}

# Sync files based on OS type
if [[ "$OSTYPE" == "darwin"* ]]; then
    sync_file zshrc
fi

# Always sync vim and tmux.conf
sync_file vim
sync_file tmux.conf

# Alacritty configuration
if command -v alacritty &>/dev/null; then
    alacritty_dir="$HOME/.config/alacritty"
    mkdir -vp "$alacritty_dir"
    ln -sfn "$HOME/.files/alacritty.toml" "$alacritty_dir/alacritty.toml" 
else
    echo "Alacritty is not installed. Please install Alacritty first."
fi

# Check for tmux installation
if ! command -v tmux &>/dev/null; then
    echo "tmux is not installed. Please install tmux first."
    exit 1
fi

# Relaunch shell
exec $SHELL

