[".config/vim/"]
  type = "git-repo"
  url = "https://github.com/rdnajac/.vim.git"
  refreshPeriod = "24h"

# [".config/vim/autoload/plug.vim"]
#   type = "file"
#   url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
#   refreshPeriod = "999h"
