[".vim/pack/chezmoi/start/chezmoi.vim"]
   type = "git-repo"
   url = "https://github.com/alker0/chezmoi.vim.git"
   refreshPeriod = "168h"

[".vim/pack/chezmoi/start/chezmoiexternal/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".vim/pack/chezmoi/start/chezmoiexternal/autoload/repeat.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/tpope/vim-repeat/refs/heads/master/autoload/repeat.vim"
    refreshPeriod = "168h"
