plugins:
- alker0/chezmoi.vim
- dstein64/vim-startuptime
- dense-analysis/ale
- junegunn/fzf.vim
- lervag/vimtex
- tpope/vim-abolish
- tpope/vim-capslock
- tpope/vim-characterize
- tpope/vim-dadbod
- tpope/vim-dispatch
- tpope/vim-endwise
- tpope/vim-eunuch
- tpope/vim-fugitive
- tpope/vim-repeat
- tpope/vim-rhubarb
- tpope/vim-rsi
- tpope/vim-scriptease
- tpope/vim-speeddating
- tpope/vim-surround
- tpope/vim-tbone
- tpope/vim-unimpaired
- tpope/vim-vinegar
