[env]
TERM = "xterm-256color"

[window]
padding = {x = 2, y = 2}
dynamic_padding = true
decorations = "full"

[colors.normal]
blue = "#14afff"
magenta = "#ff69ff"

[colors.primary]
#background = "#16161d"
background = "#000000"
foreground = "#39ff14"

[font]
size = 13.0
[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
# I think we can omit these and defaut to above
# [font.bold]
# family = "JetBrainsMonoNL Nerd Font Mono"
# [font.italic]
# family = "JetBrainsMonoNL Nerd Font Mono"
# [font.bold_italic]
# family = "JetBrainsMonoNL Nerd Font Mono"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

# disable closing window on cmd + w
[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[selection]
# Semantic Escape Characters
# same as below but in toml not yml
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true


