[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.8
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"
option_as_alt = 'OnlyLeft'

# [terminal.shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["-2", "new-session", "-A", "-s", "alacritty-sesh"]

[font]
size = 13.37
# size = 15
[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

# Tokyonight colors
[colors.primary]
background = '#000000'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
