[env]
TERM = "xterm-256color"

[window]
padding = {x = 2, y = 2}
dynamic_padding = true
#startup_mode = "SimpleFullscreen"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["-2",  "new-session", "-A", "-s", "alacritty-sesh"]

[colors.normal]
blue = "#14afff"
magenta = "#ff69ff"

[colors.primary]
background = "#000000"
foreground = "#39ff14"

[font]
size = 13.0
[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true
