" vimrc
scriptencoding utf-8

let s:VIMHOME = expand('$XDG_CONFIG_HOME/vim//')
let g:plug_home = s:VIMHOME . '/.plugged//'
let &backupdir   = s:VIMHOME . '.backup//'
let &directory   = s:VIMHOME . '.swap//'
let &undodir     = s:VIMHOME . '.undo//'
let &viminfofile = s:VIMHOME . '.viminfo'
let &spellfile   = s:VIMHOME . '.spell/en.utf-8.add'
" let &verbosefile = s:VIMHOME . '.vimlog.txt'

let g:mapleader = ' '
let g:maplocalleader = '/'

" better escape
noremap jk <esc>
noremap kj <esc>


nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>
nnoremap <localleader><Tab> :b#<CR>

" center searches
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap * *zzzv
nnoremap # #zzzv
nnoremap g* g*zzzv
nnoremap g# g#zzzv

" better completion
inoremap <silent> ,o <C-x><C-o>
inoremap <silent> ,f <C-x><C-f>
inoremap <silent> ,i <C-x><C-i>
inoremap <silent> ,l <C-x><C-l>
inoremap <silent> ,n <C-x><C-n>
inoremap <silent> ,t <C-x><C-]>
inoremap <silent> ,u <C-x><C-u>

augroup autoRestoreCursor
  autocmd!
  autocmd BufReadPost *
        \ let line = line("'\"")
        \ | if line >= 1 && line <= line("$")
        \ |   execute "normal! g`\""
        \ |   execute "silent! normal! zO"
        \ | endif
augroup END

augroup autoMkdir
  autocmd!
  autocmd BufWritePre * call file#automkdir(expand('<afile>'))
augroup END

silent! color scheme

augroup quit_on_q
  autocmd!
  autocmd FileType help,qf,man silent! nnoremap <silent> <buffer> q :<C-U>close<CR>
augroup END

" Quit command window immediately if opened accidentally
augroup noCmdwin | autocmd! | autocmd CmdwinEnter * quit |  augroup END

  call plug#begin()
  " Plug 'rdnajac/after'
  Plug 'tpope/vim-apathy'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-endwise'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-scriptease'
  Plug 'tpope/vim-sensible'
  Plug 'tpope/vim-speeddating'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-tbone'
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-vinegar'
  " only load plugins on certain filetypes
  Plug 'lervag/vimtex', { 'for': 'tex' }

  " Plug 'benekastah/neomake', has('nvim') ? {} : { 'on': [] }

  call plug#end() " executes `filetype plugin indent on` and `syntax enable`

  " vim: ft=vim fdm=marker sw=2 sts=2
