return {
  'nvim-treesitter/nvim-treesitter',
  dependencies = {
    { 'RRethy/nvim-treesitter-endwise' },
    { 'nvim-treesitter/nvim-treesitter-context', opts = {} },
    -- { 'windwp/nvim-ts-autotag', opts = {} },
    { 'folke/ts-comments.nvim', opts = {} },
  },
  opts = {
    ensure_installed = {
      -- 'asm',
      'bash',
      -- 'bibtex',
      'csv',
      'cmake',
      'cpp',
      'cuda',
      -- FIXME
      'comment', -- HACK: this is a custom parser
      'diff',
      'dockerfile',
      'doxygen',
      'git_config',
      'gitcommit',
      'git_rebase',
      'gitattributes',
      'gitignore',
      'gitcommit',
      -- 'groovy',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'jsonc',
      -- 'json5',
      'latex',
      'llvm',
      'luadoc',
      'luap',
      'make',
      'ocaml',
      'printf',
      'python',
      'rnoweb',
      'regex',
      'toml',
      'r',
      'xml',
      'yaml',
      -- these come built-in with neovim
      -- 'vim',
      -- 'vimdoc',
      -- 'c',
      -- 'lua',
      -- 'markdown',
      -- 'markdown_inline',
      -- 'query',
    },
  },
}
