os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  # theme:
  #   activeBorderColor:
  #     - "#ff9e64"
  #     - "bold"
  #   inactiveBorderColor:
  #     - "#27a1b9"
  #   searchingActiveBorderColor:
  #     - "#ff9e64"
  #     - "bold"
  #   optionsTextColor:
  #     - "#14afff"
  #   selectedLineBgColor:
  #     - "#283457"
  #   cherryPickedCommitFgColor:
  #     - "#14afff"
  #   cherryPickedCommitBgColor:
  #     - "#bb9af7"
  #   markedBaseCommitFgColor:
  #     - "#14afff"
  #   markedBaseCommitBgColor:
  #     - "#e0af68"
  #   unstagedChangesColor:
  #     - "#db4b4b"
  #   defaultFgColor:
  #     - "#c0caf5"
