[cargo]
crates = [
  "bat",
  "bottom",
  "cargo-update",
  "du-dust",
  "eza",
  "fd-find",
  "hexyl",
  "pokeget",
  "procs",
  "ripgrep",
  "shellharden",
  "so",
  "tealdeer",
  "tokei",
  # "yazi-cli",
  # "yazi-fm",
  "zoxide"
]
