[cargo]
crates = [
  # "bat",
  # "eza",
  # "fd-find",
  # "ripgrep",
  "bottom",
  "cargo-update",
  "du-dust",
  "hexyl",
  "pokeget",
  "procs",
  "so",
  "tealdeer",
  "tokei",
  # "yazi-cli",
  # "yazi-fm",
]
