[apt]
packages = [
  "build-essential",
  "cmake",
  "curl",
  "gettext",
  "git",
  "libssl-dev",
  "linux-headers-\"$(uname -r)\"",
  "make",
  "net-tools",
  "ninja-build",
  "pkg-config",
  "rsync",
  "tmux",
  "vim",
  "bat",
  "eza",
  "fd-find",
  "ripgrep",
]
