name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  clone-and-install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: ./install.sh
      - name: chezmoi data
        run: chezmoi data
